// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("API.RegistroAgua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Conductividad")
                        .HasColumnType("REAL");

                    b.Property<bool>("CumpleParametros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoGeneral")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<double>("FlujoPermeado")
                        .HasColumnType("REAL");

                    b.Property<double>("FlujoRechazo")
                        .HasColumnType("REAL");

                    b.Property<double>("Ph")
                        .HasColumnType("REAL");

                    b.Property<double>("PorcentajeRecuperacion")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("HistorialPlanta");
                });
#pragma warning restore 612, 618
        }
    }
}
